services:
  api:
    build: ./backend
    container_name: treinamento-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # variáveis para conectar ao Postgres
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: treinamento
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - dpnet

  db:
    image: postgres:14
    container_name: treinamento-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: treinamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    volumes:
      # persistência dos dados
      - pgdata:/var/lib/postgresql/data
      # seed do banco
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

networks:
  appnet:
  dpnet:

volumes:
  pgdata:
